# Site Setting
#theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Sarvagya Sagar"
description: "Trekking on the path of Recon to Exploit stuff out there."
baseurl: 
url: https://iamsarvagyaa.github.io
logo: "/images/my.jpg"
date_format: "%B %-d, %Y"
read_time: true 
words_per_minute: 200
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-194295946-1
  #disqus: 
  #shortname: https-iamsarvagyaa-github-io
twitter:
  username: "iamsarvagyaa"
    #google_site_verification: wB3aam-kuJmMCLol44dVHdg8nfUXgb7C-1s-LbqZeo4

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
#collections:
#  newsletters:
#    output: true
#    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
#  # Newsletters defaults
#  - scope:
#      path: "_newsletters"
#      type: newsletters
#    values:
#      layout: post
#      comments: true
#     share: true

# Site Author
author:
  name: Sarvagya Sagar
  picture: /images/author.png
  email: iamsarvagyaa@gmail.com
  twitter: iamsarvagyaa
  links:
    - title: Twitter
      url: https://twitter.com/iamsarvagyaa
      icon: fab fa-twitter-square
    - title: Github
      url: https://github.com/iamsarvagyaa
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://linkedin.com/in/iamsarvagyaa
      icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Twitter
    url: https://twitter.com/iamsarvagyaa
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/iamsarvagyaa
    icon: fab fa-instagram
  - title: Github
    url: https://github.com/iamsarvagyaa
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/iamsarvagyaa
    icon: fab fa-linkedin
